# Hydrogen

spacing = 3
padding = 0
hide_ascii = false
separator = "󰞷"
key_color = "Yellow"
separator_color = "Red"
prefer_small_ascii = true

[palette]
type = "Full"
glyph = "  "
visible = true

[bar]
glyph = " "
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
title = " matic "
border = "double"
visible = false

[box.inner_margin]
x = 0
y = 0

[randomize]
key_color = false
separator_color = false

[custom_ascii]
# color="red"
# path="~/.dotfiles/macchina/themes/ascii-arch.txt"

[keys]
host = " Host"
battery = "󱊦 Battery"
os = " OS"
terminal = " Terminal"
shell = " Shell"
packages = "󰏖 Packages"
memory = "󰍛 Memory"
local_ip = "󰩠 Local IP"
backlight = "󰃠 Brightness"
cpu_load = " CPU Load"
cpu = " CPU"
# gpu = " GPU"
disk_space = " Disk Space"
