require("matic.options")
require("matic.lazy")
require("matic.keymaps")
require("matic.highlight_yank")
require("matic.format_on_save")
require("matic.toggle_eslint")
require("matic.rotate_windows")
require("matic.resize_windows")
require("matic.vertical_help")
require("matic.edit_text")
-- require("matic.kitty_autocmds")
require("matic.toggle_diagnostics")
