name: Format and Update

on:
  push:
    branches:
      - main

jobs:
  format-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format"

      - name: Update Snippets
        run: pnpm run update-snippets

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snippets"
          file_pattern: README.md package.json
