spec("bqf")
spec("cellular-automaton")
-- spec "colorizer"
spec("copilot")
spec("dressing")
spec("eyeliner")
spec("fidget")
spec("gitlinker")
spec("lab")
spec("modicator")
spec("navbuddy")
spec("neoscroll")
spec("neotab")
spec("nvim-nio")
spec("oil")
spec("tabby")
spec("tabnine")
spec("ufo")
